import { useState } from "react"
import { Button } from "./ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs"
import { Badge } from "./ui/badge"
import { LogOut, GraduationCap, Calendar, BarChart3 } from "lucide-react"
import type { User } from "../App"
import { AttendanceMarking } from "./attendance-marking"
import { AttendanceReports } from "./attendance-reports"
